name: Build LaTeX document
on: [push]
jobs:
  build_latex_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Install dependencies
        run: python -m pip install pygments # minted highlight for LaTeX
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: thesis.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Thesis
          path: thesis.pdf
      - name: Github Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: thesis.pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}